- .circleci/config.yml
Signed-off-by: Afshin Paydar <afshin.paydar@binary.com>
> Change bot.binary.com to bot.deriv.com

- src/botPage/view/LogTable.js
- src/botPage/view/TradeInfoPanel/index.js
- static/css/deriv/index.scss
> Mehrzad / update-responsive

- src/botPage/view/tour/welcome.js
- static/css/_tour.scss
Reverts deriv-com/binary-bot#43
> Revert "Updated tour pointers - usability"

- src/botPage/view/View.js
> Mehrzad / remove update logo

- src/botPage/view/TradeInfoPanel/TradeTable.js
- src/botPage/view/TradeInfoPanel/index.js
- src/botPage/view/shared.js
> refactor: replace class component with functional one

- src/botPage/view/TradeInfoPanel/AnimateTrade.js
- src/botPage/view/TradeInfoPanel/index.js
- src/common/hooks/isMounted.js
- static/css/deriv/index.scss
This PR is to convert `TradeInfoPanel` to a functional component and make the summary panel to show up as full page on mobile devices.
> salar / Refactor/tradeinfopanel to functional

- static/css/deriv/index.scss
> salar / Fix: set correct height for summary to show stop warning

- .circleci/config.yml
- .gitignore
- README.md
- package-lock.json
- package.json
- src/botPage/common/google_drive_config.js
- src/botPage/view/Dialogs/Dialog.js
- src/botPage/view/View.js
- src/botPage/view/deriv/layout/ToolBox/ToolBox.jsx
- src/botPage/view/deriv/layout/ToolBox/common/index.js
- src/botPage/view/deriv/layout/ToolBox/components/load/load.jsx
- src/botPage/view/deriv/layout/ToolBox/components/loading_button/index.js
- src/botPage/view/deriv/layout/ToolBox/components/loading_button/loading_button.jsx
- src/botPage/view/deriv/layout/ToolBox/components/reset/reset.jsx
- src/botPage/view/deriv/layout/ToolBox/components/save/save.jsx
- src/botPage/view/deriv/store/client-slice.js
- src/botPage/view/deriv/store/ui-slice.js
- src/botPage/view/react-components/Integrations/GoogleDriveIntegration.js
- src/botPage/view/trackJs_config.js
- src/common/integrations/GoogleDrive.js
- src/common/utils/tools.js
- webpack.config.cli.js
- webpack.config.web.js
This PR is to refactor Google Drive helper components to functional.
Including:
- **src/common/integrations/GoogleDrive.js**
- **src/botPage/view/react-components/Integrations/GoogleDriveIntegration.js**
- **src/botPage/view/deriv/layout/ToolBox/components/load/load.jsx**
- **src/botPage/view/deriv/layout/ToolBox/components/save/save.jsx**
Also fixes some of the _TrackJS_ errors we already face.
It will enable **Google Drive** testing in _local_, _staging_ and _test-link deployments_ too.
And puts the environment secrets to `.env` to prevent access by 3rd-parties.
> Refactor | Google Drive to functional | Iteration #1

- src/botPage/view/Dialogs/Limits.js
- src/botPage/view/View.js
- src/botPage/view/blockly/blocks/trade/index.js
> Sara / Fixed issue with refresh button

- src/botPage/view/index.js
> Sara / Fixed issue with client accounst

- src/botPage/view/deriv/layout/Header/Header.jsx
- src/botPage/view/deriv/utils/account-methods.js
- src/botPage/view/index.js
- src/common/utils/storageManager.js
> Sara / Reverted convertToDeriv

- src/common/utils/storageManager.js
> Sara / Fixed issue with convert method

- src/botPage/view/deriv/layout/Error/bot-unavailable-message-page.jsx
- src/botPage/view/deriv/utils/deriv-links.js
- src/common/appId.js
Reverts deriv-com/binary-bot#118
> Revert "Mehrzad / update unavailable  page links"

- src/botPage/view/LogTable.js
- src/botPage/view/deriv/layout/Header/Header.jsx
- src/botPage/view/deriv/layout/Header/components/tab-content.jsx
> Sandeep - Fixed logtable UI issue along with switching account fix

- src/botPage/view/LogTable.js
We no longer need the scroll feature, So I have removed scroll feature and related components.
> Fixed autoscroll to bottom logtable

- src/botPage/view/Dialogs/Chart.js
- src/botPage/view/blockly/blocks/trade/tradeOptions.js
added Workaround to fix the basket-indices chart.
> Fix  basket indices chart

- src/botPage/view/deriv/layout/ToolBox/ToolBox.jsx
> Sara / Added e.preventdefault and removed deprecated property

- src/botPage/view/deriv/blockly-worksace.js
- src/botPage/view/deriv/components/popover/popover.jsx
- src/botPage/view/deriv/layout/ToolBox/ToolBox.jsx
- static/css/_toolbox.scss
Reverts deriv-com/binary-bot#170
> Revert "MaryiaF_67322/fix: hide action buttons in the toolbox when the needed data …"

- .circleci/config.yml
| Tests Added + Pass?      | No
| Does not reduce coverage?| No
> Prince/ force fetching of tags temporarily

- gulp/build.js
- package.json
- src/botPage/view/deriv/layout/Main/main.jsx
- templates/deriv/index.mustache
Reverts deriv-com/binary-bot#188
> Revert "MaryiaF/feat: add seo for pages"

- src/common/integrations/GoogleDrive.js
> Sara / Fixed issue with disable cookies to load google drive

- src/botPage/bot/TradeEngine/Purchase.js
- src/botPage/common/ChartTicksService.js
- src/botPage/common/TicksService.js
- src/botPage/common/symbolApi/index.js
- src/botPage/view/Dialogs/Chart.js
- src/botPage/view/NetworkMonitor.js
- src/botPage/view/TradeInfoPanel/TradeTable.js
- src/botPage/view/blockly/index.js
- src/botPage/view/deriv/layout/Footer/components/network-status.jsx
- src/botPage/view/deriv/layout/Footer/components/server-time.jsx
- src/botPage/view/deriv/layout/Main/main.jsx
- src/botPage/view/deriv/store/index.js
- src/botPage/view/react-components/HeaderWidgets.js
- src/common/utils/tools.js
Fixed: Added catch statements for api calls and globalobserver error emitter.
Fixed: npm run test Warnings
Fixed: import sequence
> Worked on trackjs issue

- .babelrc
- package-lock.json
- package.json
Updated core-js package to 3.18 from 2.6.5
| Patch: Bug Fix?          | `fixed trackjs bug`
> Updated corejs package to fix the replaceAll polyfill

- src/botPage/view/LogTable.js
- src/common/integrations/trackJSTrack.js
Fixed virtualized-table related warnings of LogTable component
Added the false/undefined/null check for the code in the trackjsTrack file
> Fix  trackjs undefined 1

- src/common/integrations/GoogleDrive.js
> Sara / Changed message related to cookie issue on GD

- src/common/integrations/GoogleDrive.js
> Sara / Made the message shorter

- src/botPage/view/blockly/index.js
> Sara / Removed unnecessary trackjs log

- src/botPage/view/deriv/api.js
- src/botPage/view/deriv/layout/Endpoint/Endpoint.jsx
- src/common/appId.js
> Sara / Added deriv=brand

- .github/pull_request_template.md
-   Edit pull request template to align to other repositories
-   [x] Script configuration
> Align pull_request_template to other repositories

- templates/deriv/localstorage-sync.mustache
> Prince/ auto login on bot from derivp app

- templates/deriv/localstorage-sync.mustache
> Prince/ fix message handling for iframes

- templates/deriv/localstorage-sync.mustache
Reverts deriv-com/binary-bot#226
> Revert "Prince/ fix message handling for iframes"

- templates/deriv/localstorage-sync.mustache
Reverts deriv-com/binary-bot#225
> Revert "Prince/ auto login on bot from derivp app"

- templates/deriv/index.mustache
- templates/deriv/localstorage-sync.mustache
> Prince/ store cookies and auto-login on visit

- templates/deriv/localstorage-sync.mustache
> Prince/ additional handler for SSO

- templates/deriv/index.mustache
- templates/deriv/localstorage-sync.mustache
> Prince/ Additional fix for sso

- package.json
> Vinu/added eslint-plugin-prettier package

- src/botPage/common/google_drive_config.js
> Vinu/fix: import strategy fix for google drive

- src/common/integrations/GoogleDrive.js
> Vinu/fix: avoid user logout when invalid xml is loaded

- src/common/integrations/GoogleDrive.js
> Vinu/fix: google drive 500 error on upload

- src/botPage/bot/Interpreter.js
- src/botPage/bot/TradeEngine/Proposal.js
- src/botPage/common/TicksService.js
-   Fixed notification flooding issue
> fix: fixed error flooding

- gulp/build.js
- templates/deriv/index.mustache
> Fix: binary bot meta tag preview issue

- templates/deriv/index.mustache
> Feat: Place survicate script

- src/app.config.js
- src/common/i18n.js
-   fix: remove Indonesian language in the language option
-   [x] New feature
> Maryia/92225/fix: remove indonesian language in the language option

- templates/deriv/localstorage-sync.mustache
Reverts deriv-com/binary-bot#258
> Revert "fix: for local storage sync"

- templates/deriv/localstorage-sync.mustache
Reverts deriv-com/binary-bot#282
> Revert "fix: local storage sync"

- .circleci/config.yml
- Upgrade image used for deployment
-   [x] Script configuration
> Upgrade deployment image only used for publishing

- src/app.config.js
- src/botPage/view/deriv/layout/Footer/components/language-selector.jsx
- src/common/i18n.js
- static/css/deriv/settings-language.scss
Added new languages ru, fr, th, vi
> fix: add languages ru, fr, th, vi

- src/common/integrations/GoogleDrive.js
-   TrackJS - There was an error loading Google Drive API script. - Error: {"isTrusted":true}
> Maryia/Bot-411/TrackJS - There was an error loading Google Drive API script. - Error: {"isTrusted":true} and Google Identity API 

- src/botPage/view/TradeInfoPanel/AnimateTrade.js
- src/botPage/view/TradeInfoPanel/ClearButton.js
-   fix: Close the bot when there is no defined step on block 4
-   [x] Update feature
> Maryia/Bot-203/fix: Close the bot when there is no defined step on block 4

- .eslintrc
- Fixed react version in eslint config
> chore: :bug: fixed the react version in eslint

- .circleci/config.yml
- updated circle-ci to rerun all the action
> chore: updated circle-ci to rerun all the actions

- .circleci/config.yml
- webpack.config.cli.js
fix: changed mode to node for production build also reverted circle changes
> fix: changed mode to node for production build

- .circleci/config.yml
- experimental change in config to check if it works
> fix: updated node version in circle ci config

- .circleci/config.yml
- experimental change in config to fix the underlying issue
from 
```
docker_latest_image_tag:
type: string
default: "latest"
```
to 
```
docker_latest_image_tag:
type: string
default: "latest-staging"
```
> fix: changed back latest to latest-staging in circleci config

- .circleci/config.yml
Updated node version for circle-ci production env
> fix: :fire: updated node version for production env

- src/botPage/view/blockly/index.js
-   fix: TrackJS - Cannot read properties of undefined (reading 'getField')
> Maryia/BOT-416/fix: TrackJS - Cannot read properties of undefined (reading 'getField')

- src/common/integrations/GoogleDrive.js
-   fix: Track JS - GoogleDrive
> Maryia/Bot-413/fix: Track JS - GoogleDrive

- public/index.html
-   Upload type changed from .xml to application/xml text/xml
> fix: :fire: updated the xml accept type

- src/storage.js
Removed regex to check for lang in the URL
> fix: :fire: fixed unable to login issue

- src/assets/css/bot.scss
- src/botPage/common/ChartTicksService.js
- src/botPage/common/TicksService.js
- src/botPage/view/Dialogs/TradingView.js
- src/botPage/view/blockly/index.js
- src/botPage/view/deriv/blockly-worksace.js
- src/botPage/view/deriv/layout/Main/main.jsx
- src/botPage/view/deriv/layout/ToolBox/ToolBox.jsx
- src/botPage/view/deriv/layout/ToolBox/components/reset/reset.jsx
- src/botPage/view/deriv/routes/Routes.jsx
- src/botPage/view/logger.js
- src/botPage/view/style.js
- src/config.js
- webpack.config.js
Fixed trackjs issue {${some error}}
It was happening because for some of the promises catch was not being handled properly,
to be precise, in the authorize, ticksService and ticks_history
> fix: :fire: Trackjs fixed  issue

- .circleci/config.yml
Just removed the k8s and docker config as we dont need them any more.
-   ...
-   [x] Script configuration
-   [x] Release
> Ako/ remove docker and k8s config as they are not valid anymore

- src/components/Dialogs/IntegrationsDialog.js
- src/components/GoogleDriveIntegration.js
> refactor: :fire: fixed google drive integration dialog

- src/botPage/common/google_drive_config.js
Reverted the scope of google drive user to recommended scope.
> fix: revert the scope of google drive to recomended one

- public/localstorage-sync.html
- src/blockly/customBlockly.js
- src/components/Header/account-actions.jsx
- src/utilities/logger.js
- The following TrackJS issue has been resolved
- Also removed unnecessary consoles
> hotfix: :fire: Trackjs - fixed unable to desctructure issue

- src/blockly/customBlockly.js
Added optional chaining to avoid null
> chore: added optional chaining to avoid null

- src/botPage/common/google_drive_config.js
> fix: change the scope of google drive

- src/botPage/common/google_drive_config.js
Reverts deriv-com/binary-bot#359
> Revert "fix: change the scope of google drive"

- src/blockly/bot/Interface/WebhookInterface.js
- src/blockly/bot/broadcast.js
- src/utilities/integrations/GoogleDrive.js
Added changes to get more info or error when error occurs while using webhook block
> fix: added trackJs error to collect more info

- src/blockly/index.js
> Rupato/BOT-868/fix: for trackJS error

- public/index.html
- Removed survicate code snippet as survicate tool will no longer be used for tracking and the tool will be discontinued. We will be replacing it with hotjar tool
> [BOT] Farabi/bot-984/remove survicate on binary bot

- src/components/Banner/move-to-dbot-banner.scss
- src/components/common/deriv-app-modal/deriv-app-modal.jsx
- src/components/common/deriv-app-modal/deriv-app-modal.scss
https://app.clickup.com/t/20696747/WEBREL-1684
- Issue: the pop-up design on Binary Bot is not similar to the production
- Changed the class names for the Dbot like modal so it that it doesn't collide with Binary Bot modals
> [BOT] chore: bbot modal style issue

- src/components/Banner/move-to-dbot-banner.jsx
- https://app.clickup.com/t/20696747/BOT-1128
- Added a custom query param to the URL while redirecting to Dbot from the Binary Bot redirection banner
> [BOT] chore: add query param to the redirection url

- .github/actions/build_and_push_docker_image/action.yml
- .github/workflows/release_production.yml
- .github/workflows/release_staging.yml
I need to enable docker image creation and k8s orchestration on our release process as backup for the release process on binary-bot
> Added docker deployment action and workflows

- .github/workflows/generate_preview_link.yml
- .github/workflows/pre_generate_preview_link.yml
This pull request (PR) adds deployment testing links for PR testing on Binary Bot. The feature incorporates links to facilitate testing of the pull request within the Binary Bot environment. This addition aims to streamline the testing process and ensure that the changes made in the PR can be easily and efficiently tested in the Binary Bot deployment.
> Akmal / feat: add PR testing links deployment on binary bot

- src/blockly/blockly-worksace.js
- src/blockly/bot/Interpreter.js
- src/blockly/bot/TradeEngine/index.js
- src/botPage/common/TicksService.js
- src/utils.js
> [Bot]fix: handle already subscribed error

- src/blockly/blockly-worksace.js
- src/blockly/bot/Interpreter.js
- src/blockly/bot/TradeEngine/index.js
- src/blockly/bot/__tests__/StopStart.js
- src/blockly/index.js
- src/botPage/common/TicksService.js
Handled alreadySubscribed error when other error arise.
> [Bot]fix: fixed all scenario where already-subscribed error is appearing

- src/components/Draggable/DraggableResizeWrapper.jsx
Added a logic to show the chart once the calculation is done and the chart is centered on the screen based on scrolling behaviour.
> [BOT] chore: show chart once it's centered

- src/components/Draggable/DraggableResizeWrapper.jsx
Reverts deriv-com/binary-bot#404
> Revert "[BOT] chore: show chart once it's centered"

- src/blockly/blockly-worksace.js
- src/botPage/common/TicksService.js
handled already subscribed error for strategies with candle block by unsubscribing the candles
> [Bot]fix: handled already subscribed error for strategies with candle block

- src/components/Dialogs/Chart.js
Forget all call should happen based on granularity
> [Bot] chore: call forget all based on granularity

- src/assets/css/index.scss
- src/components/Header/WalletAccountSwitcher/account-wallet-dropdown.jsx
- src/components/Header/WalletAccountSwitcher/account-wallet-dropdown.scss
- src/components/Header/menu-links.jsx
- src/config.js
1. replace the 'deposit' button with 'manage funds' and no redirect
2. ui for the mobile version of the wallet account switcher
3. add event handlers
> [BOT]Maryia/feature-wallet-switcher: fix bugs

- src/storage.js
> Rupato/fix: logout issue

- src/assets/css/_panel.scss
Styles of previous JQuery Modals were left our for a few of the modals that are using the table. Added the styles for the draggable component as well to support those.
> [BOT] fix: style issue related to modal

- .github/actions/build/action.yml
- .github/workflows/generate_preview_link.yml
- .github/workflows/release_production.yml
- .github/workflows/release_staging.yml
- package-lock.json
- package.json
- src/api-base.js
- src/api-middleware.js
- src/blockly/blockly-worksace.js
- src/utilities/utility-functions.js
- webpack.config.cli.js
Added api middleware and datadog setup to capture logs in binary bot.
> [Bot]feat: :sparkles: added datadog setup

- package-lock.json
- package.json
Updated outdated packages: 😞 
- @babel/core
- @babel/preset-env
> chore: updated outdate deps

- src/constants.js
- src/routes/Routes.jsx
- src/storage.js
Updated URLS in Official bot domains list
bot.deriv.com
bot.deriv.be
bot.deriv.me
staging-bot.deriv.com
staging-bot.deriv.be
staging-bot.deriv.me
> fix: :fire: updated list of official binary-bot domains

- src/assets/css/_dbot-banner.scss
- src/assets/css/_mixins.scss
- src/assets/css/_variables.scss
- src/assets/css/bot.scss
- src/assets/css/index.scss
- src/blockly/index.js
- src/common/appId.js
- src/components/Banner/fixed-dbot-banner.jsx
- src/components/Banner/fixed-dbot-banner.scss
- src/components/Banner/move-to-dbot-banner.jsx
- src/components/Banner/redirect-to-dbot.js
- src/components/Error/bot-unavailable-message-page.jsx
- src/components/Header/platform-dropdown.jsx
- src/components/Main/main.jsx
- src/config.js
- src/storage.js
- src/utils.js
- webpack.config.js
- Created a permanent banner to move to deriv for binary bot)
> [BOT] Farabi/bot-1338/add-permanent-banner-to-bbot

- .github/actions/build_and_push_docker_image/action.yml
- .github/actions/send_slack_notifications/action.yml
- .github/actions/versioning/action.yml
Updated following GitHub workflows
- `build_and_push_docker_image/action.yml`
- `send_slack_notifications/action.yml`
- `versioning/action.yml`
NA
> chore: working on workflows to mitigate the issues

- .github/actions/build_and_push_docker_image/action.yml
> chore: fixed var issue

- .github/actions/build_and_push_docker_image/action.yml
Reverts deriv-com/binary-bot#437
> Revert "chore: fixed var issue"

- .github/actions/build_and_push_docker_image/action.yml
- .github/actions/send_slack_notifications/action.yml
- .github/actions/versioning/action.yml
Reverts deriv-com/binary-bot#436
> Revert "chore: working on workflows to mitigate the issues"

- .github/actions/versioning/action.yml
GitHub workflow changes
- Updated versioning workflow
> chore: fixing the versioning workflow

- .github/actions/send_slack_notifications/action.yml
> chore: added vars back to steps instead of glob

- .github/actions/send_slack_notifications/action.yml
> chore: fixed indentation and var input

- .github/actions/send_slack_notifications/action.yml
> chore: updated vars to inputs

- .github/actions/send_slack_notifications/action.yml
> chore: added custom job in the workflow -- experimental

- .github/actions/send_slack_notifications/action.yml
- .github/workflows/release_staging.yml
> chore: updated vars for failing step

- .github/actions/send_slack_notifications/action.yml
> chore: removed env from the steps

- .github/actions/build_and_push_docker_image/action.yml
- .github/workflows/release_staging.yml
> chore: added vars to docker workflow

- .github/actions/build_and_push_docker_image/action.yml
> chore: added missing vars

- .github/actions/send_slack_notifications/action.yml
- .github/workflows/release_production.yml
- .github/workflows/release_staging.yml
- Added staging workflow back
- added app_url for better readability of the slack message and ease to click URL
> chore: uncommented slack notification for staging

- src/assets/css/bot.scss
- src/assets/css/index.scss
- src/components/Header/WalletAccountSwitcher/wallet-content.jsx
- src/components/Header/WalletAccountSwitcher/wallet-icon.jsx
- src/components/Header/WalletAccountSwitcher/wallet-icon.scss
- src/components/Header/account-actions.jsx
- src/components/Header/account-menu.jsx
- src/constants.js
- src/storage.js
- Mobile responsive - BBot header icons and notification icon position are different from the design.
- Moved the notification bell icon to the right side of the account switcher if the account is wallets
> fix: :fire: fixed issues with header icons for wallets

- src/config.js
- Update the URL of the trader's hub to [https://app.deriv.com](https://app.deriv.com)
> chore: :fire: updated dtrader URL

- public/index.html
Added experimental GTM for binary-bot
> chore: :bulb: added gtm code snippet for the binary bot

- .github/workflows/release_production.yml
- .github/workflows/release_staging.yml
- .gitignore
- vercel.dr.json
This Pr implements Disaster Recovery using vercel. 
Removed previous implementation of dr using docker and kubernetes.
> Meenu/feature: dr implementation

- src/components/Banner/move-to-dbot-banner.jsx
- src/components/Banner/move-to-dbot-banner.scss
- updated migration content on the weekly popup 
- Update date on both weekly and permanent static banner
> Sandeep/bot 1933/update deprication content

- .github/workflows/release_production.yml
Fixed release production yml update
> fix: release production yml update

- .gitignore
Updated gitignore with 
.env
.env.*
*.env
> :chore :fire: updated gitignore
